#MongoDB Stack
#Single Node
#Optional: CODE

version: '3.8'

networks:
  public:
    
volumes:
  data:

secrets:
  mongo_initdb_root_username:
    external: true
    name: ${MONGO_INITDB_ROOT_USERNAME}
  mongo_initdb_root_password:
    external: true
    name: ${MONGO_INITDB_ROOT_PASSWORD}
  
services:
  mongo:
    image: ${MONGO_IMAGE}
    volumes:
      - data:/data/db
    ports:
      - "${STACK_CODE}17:27017"
    networks:
      - public
    secrets:
      - mongo_initdb_root_username
      - mongo_initdb_root_password
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/mongo_initdb_root_username
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo_initdb_root_password
    deploy:
      resources:
        limits:
          cpus: ${MONGO_CPU_LIMIT}
          memory: ${MONGO_MEMORY_LIMIT}
        reservations:
          cpus: ${MONGO_CPU_RESERVATION}
          memory: ${MONGO_MEMORY_RESERVATION}
      placement:
        constraints:
          - node.labels.${NODE_LABEL} == 1 

