#MongoDB Stack
#Single Node
#Optional: CODE

version: '3.8'

networks:
  mongodb-public:
    external: true
    
volumes:
  v326_data:
  v507_data:

secrets:
  mongo_initdb_root_username:
    external: true
  mongo_initdb_root_password:
    external: true
  
services:
  v507:
    image: ${MONGO_507_IMAGE}
    volumes:
      - v507_data:/data/db
    ports:
      - "${CODE-52}507:27017"
    networks:
      - mongodb-public
    secrets:
      - mongo_initdb_root_username
      - mongo_initdb_root_password
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/mongo_initdb_root_username
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo_initdb_root_password
    deploy:
      resources:
        limits:
          cpus: ${MONGO_507_CPU_LIMIT}
          memory: ${MONGO_507_MEMORY_LIMIT}
        reservations:
          cpus: ${MONGO_507_CPU_RESERVATION}
          memory: ${MONGO_507_MEMORY_RESERVATION}
      placement:
        constraints:
          - node.labels.mongodb.v507 == 1 
  v326:
    image: ${MONGO_326_IMAGE}
    volumes:
      - v326_data:/data/db
    ports:
      - "${STACK_CODE}326:27017"
    networks:
      - public
    secrets:
      - mongo_initdb_root_username
      - mongo_initdb_root_password
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/mongo_initdb_root_username
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo_initdb_root_password
    deploy:
      resources:
        limits:
          cpus: ${MONGO_326_CPU_LIMIT}
          memory: ${MONGO_326_MEMORY_LIMIT}
        reservations:
          cpus: ${MONGO_326_CPU_RESERVATION}
          memory: ${MONGO_326_MEMORY_RESERVATION}
      placement:
        constraints:
          - node.labels.mongodb.v326 == 1 

