version: '3.8'


networks:
  mongodb-public:
    external: true
    
volumes:
  data:
  
services:
  v326:
    image: mongo:3.2.6
    volumes:
      - data:/data/db
    ports:
      - "${326_PORT}:27017"
    networks:
      - mongodb-public
    deploy:
      resources:
        limits:
          cpu: '1'
          memory: 300M
        reservations:
          cpus: '0.2'
          memory: 50M
        placement:
          constraints:
            - node.labels.mongodb == v326 

