#MongoDB Stack
#Single Node
#Optional: CODE

version: '3.8'

networks:
  mongodb-public:
    external: true
    
volumes:
  v326_data:

secrets:
  mongo_initdb_root_username:
    external: true
  mongo_initdb_root_password:
    external: true
  
services:
  v326:
    image: mongo:3.2.6
    volumes:
      - v326_data:/data/db
    ports:
      - "${CODE-52}326:27017"
    networks:
      - mongodb-public
    secrets:
      - mongo_initdb_root_username
      - mongo_initdb_root_password
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/mongo_intidb_root_username
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo_initdb_root_password
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 300M
        reservations:
          cpus: '0.2'
          memory: 50M
      placement:
        constraints:
          - node.labels.mongodb.v326 == 1 

